sudo: True

# Do not choose a language; we provide our own build tools.
language: generic

before_install:
- travis_retry curl -L https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz | tar xz
- travis_retry curl -L https://downloads.haskell.org/~ghc/8.4.1/ghc-8.4.1-x86_64-deb8-linux.tar.xz | tar xJ
- sudo cp -r SFML-2.4.2/include/* /usr/local/include
- sudo cp -r SFML-2.4.2/lib/* /usr/lib
- sudo apt-get install cabal-install
- cabal update
- cabal install random-1.1
- cd ghc-8.4.1
- ./configure
- sudo make install
- cd ..

install:
# Build dependencies
- make force 
